// @generated by `cargo xtask codegen` from ../E2B/spec — DO NOT EDIT BY HAND.
#![allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
#![allow(dead_code, unused_imports, missing_docs)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`Error`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"required\": ["]
#[doc = "    \"code\","]
#[doc = "    \"message\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"code\": {"]
#[doc = "      \"description\": \"Error code\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"message\": {"]
#[doc = "      \"description\": \"Error message\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Error {
    #[doc = "Error code"]
    pub code: ::std::string::String,
    #[doc = "Error message"]
    pub message: ::std::string::String,
}
impl ::std::convert::From<&Error> for Error {
    fn from(value: &Error) -> Self {
        value.clone()
    }
}
#[doc = "`VolumeDirectoryListing`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"array\","]
#[doc = "  \"items\": {"]
#[doc = "    \"$ref\": \"#/definitions/VolumeEntryStat\""]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct VolumeDirectoryListing(pub ::std::vec::Vec<VolumeEntryStat>);
impl ::std::ops::Deref for VolumeDirectoryListing {
    type Target = ::std::vec::Vec<VolumeEntryStat>;
    fn deref(&self) -> &::std::vec::Vec<VolumeEntryStat> {
        &self.0
    }
}
impl ::std::convert::From<VolumeDirectoryListing> for ::std::vec::Vec<VolumeEntryStat> {
    fn from(value: VolumeDirectoryListing) -> Self {
        value.0
    }
}
impl ::std::convert::From<&VolumeDirectoryListing> for VolumeDirectoryListing {
    fn from(value: &VolumeDirectoryListing) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<::std::vec::Vec<VolumeEntryStat>> for VolumeDirectoryListing {
    fn from(value: ::std::vec::Vec<VolumeEntryStat>) -> Self {
        Self(value)
    }
}
#[doc = "`VolumeEntryStat`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"atime\","]
#[doc = "    \"ctime\","]
#[doc = "    \"gid\","]
#[doc = "    \"mode\","]
#[doc = "    \"mtime\","]
#[doc = "    \"name\","]
#[doc = "    \"path\","]
#[doc = "    \"size\","]
#[doc = "    \"type\","]
#[doc = "    \"uid\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"atime\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    },"]
#[doc = "    \"ctime\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    },"]
#[doc = "    \"gid\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"format\": \"uint32\""]
#[doc = "    },"]
#[doc = "    \"mode\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"format\": \"uint32\""]
#[doc = "    },"]
#[doc = "    \"mtime\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"format\": \"date-time\""]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"path\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"size\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"format\": \"int64\""]
#[doc = "    },"]
#[doc = "    \"target\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"unknown\","]
#[doc = "        \"file\","]
#[doc = "        \"directory\","]
#[doc = "        \"symlink\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"uid\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"format\": \"uint32\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct VolumeEntryStat {
    pub atime: ::chrono::DateTime<::chrono::offset::Utc>,
    pub ctime: ::chrono::DateTime<::chrono::offset::Utc>,
    pub gid: u32,
    pub mode: u32,
    pub mtime: ::chrono::DateTime<::chrono::offset::Utc>,
    pub name: ::std::string::String,
    pub path: ::std::string::String,
    pub size: i64,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub target: ::std::option::Option<::std::string::String>,
    #[serde(rename = "type")]
    pub type_: VolumeEntryStatType,
    pub uid: u32,
}
impl ::std::convert::From<&VolumeEntryStat> for VolumeEntryStat {
    fn from(value: &VolumeEntryStat) -> Self {
        value.clone()
    }
}
#[doc = "`VolumeEntryStatType`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"unknown\","]
#[doc = "    \"file\","]
#[doc = "    \"directory\","]
#[doc = "    \"symlink\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VolumeEntryStatType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "directory")]
    Directory,
    #[serde(rename = "symlink")]
    Symlink,
}
impl ::std::convert::From<&Self> for VolumeEntryStatType {
    fn from(value: &VolumeEntryStatType) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for VolumeEntryStatType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Unknown => f.write_str("unknown"),
            Self::File => f.write_str("file"),
            Self::Directory => f.write_str("directory"),
            Self::Symlink => f.write_str("symlink"),
        }
    }
}
impl ::std::str::FromStr for VolumeEntryStatType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "unknown" => Ok(Self::Unknown),
            "file" => Ok(Self::File),
            "directory" => Ok(Self::Directory),
            "symlink" => Ok(Self::Symlink),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VolumeEntryStatType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for VolumeEntryStatType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VolumeEntryStatType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
