//! Shared helpers for writing generated code into the SDK source tree.

// Items are unused until Task 2 wires generators; suppress until then.
#![allow(dead_code)]

use std::path::Path;

/// Header prepended to every vendored file: marks it generated and exempts it
/// from the workspace lints (it is `pub(crate)`, so `missing_docs` never fires;
/// these allows cover clippy + dead code for code with no caller yet).
pub const GENERATED_HEADER: &str = "\
// @generated by `cargo xtask codegen` from ../E2B/spec — DO NOT EDIT BY HAND.
#![allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
#![allow(dead_code, unused_imports, missing_docs)]
";

/// Prepend [`GENERATED_HEADER`], format with rustfmt, and write to `out_path`
/// (creating parent directories). Returns an error rather than panicking.
pub fn write_generated(out_path: &Path, body: &str) -> anyhow::Result<()> {
    let with_header = format!("{GENERATED_HEADER}\n{body}\n");
    let formatted = rustfmt(&with_header)?;
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, formatted)?;
    Ok(())
}

/// Format Rust source via the `rustfmt` binary; falls back to the unformatted
/// source if rustfmt is unavailable (the file still compiles).
fn rustfmt(src: &str) -> anyhow::Result<String> {
    use std::io::Write;
    use std::process::{Command, Stdio};

    // Spawn rustfmt; if it isn't installed, return the source unformatted.
    let mut child = match Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
    {
        Ok(child) => child,
        Err(_) => return Ok(src.to_string()),
    };

    // Write the source to rustfmt's stdin (drop the handle to signal EOF).
    if let Some(mut stdin) = child.stdin.take() {
        stdin.write_all(src.as_bytes())?;
    }

    let output = child.wait_with_output()?;
    if output.status.success() {
        Ok(String::from_utf8(output.stdout)?)
    } else {
        Ok(src.to_string())
    }
}
