//! Generated envd protobuf message types (proto3-JSON serde). Generated by
//! `cargo xtask codegen`; see the per-module files.

pub(crate) mod filesystem;
pub(crate) mod process;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entry_info_round_trips_proto3_json() {
        // proto3 JSON: int64 -> quoted string, enum -> full proto name,
        // snake_case -> camelCase, optional None omitted.
        let json = r#"{
            "name": "hello.txt",
            "type": "FILE_TYPE_FILE",
            "path": "/tmp/hello.txt",
            "size": "42",
            "mode": 420,
            "permissions": "rw-r--r--",
            "owner": "root",
            "group": "root"
        }"#;
        let info: filesystem::EntryInfo =
            serde_json::from_str(json).expect("deserialize EntryInfo");
        assert_eq!(info.name, "hello.txt");
        assert_eq!(info.path, "/tmp/hello.txt");
        assert_eq!(info.size, 42); // int64 parsed from "42"
        // FileType::File == 1 (prost strips the FILE_TYPE_ prefix on the variant)
        assert_eq!(info.r#type, filesystem::FileType::File as i32);

        // Re-serialize: size becomes a quoted string again, type the full name.
        let back = serde_json::to_value(&info).expect("serialize EntryInfo");
        assert_eq!(back["size"], serde_json::json!("42"));
        assert_eq!(back["type"], serde_json::json!("FILE_TYPE_FILE"));
    }

    #[test]
    fn process_config_constructs() {
        let cfg = process::ProcessConfig {
            cmd: "/bin/bash".to_string(),
            args: vec!["-l".to_string(), "-c".to_string()],
            envs: std::collections::HashMap::new(),
            cwd: Some("/home/user".to_string()),
        };
        let json = serde_json::to_value(&cfg).expect("serialize ProcessConfig");
        assert_eq!(json["cmd"], serde_json::json!("/bin/bash"));
    }
}
