// @generated by `cargo xtask codegen` from ../E2B/spec — DO NOT EDIT BY HAND.
#![allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]
#![allow(dead_code, unused_imports, missing_docs)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`EntryInfo`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"required\": ["]
#[doc = "    \"name\","]
#[doc = "    \"path\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"metadata\": {"]
#[doc = "      \"description\": \"User-defined metadata stored as extended attributes on the file.\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"additionalProperties\": {"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"description\": \"Name of the file\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"path\": {"]
#[doc = "      \"description\": \"Path to the file\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"description\": \"Type of the file\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"file\""]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EntryInfo {
    #[doc = "User-defined metadata stored as extended attributes on the file."]
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
    )]
    pub metadata: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    #[doc = "Name of the file"]
    pub name: ::std::string::String,
    #[doc = "Path to the file"]
    pub path: ::std::string::String,
    #[doc = "Type of the file"]
    #[serde(rename = "type")]
    pub type_: EntryInfoType,
}
impl ::std::convert::From<&EntryInfo> for EntryInfo {
    fn from(value: &EntryInfo) -> Self {
        value.clone()
    }
}
#[doc = "Type of the file"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"Type of the file\","]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"file\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum EntryInfoType {
    #[serde(rename = "file")]
    File,
}
impl ::std::convert::From<&Self> for EntryInfoType {
    fn from(value: &EntryInfoType) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for EntryInfoType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::File => f.write_str("file"),
        }
    }
}
impl ::std::str::FromStr for EntryInfoType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "file" => Ok(Self::File),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for EntryInfoType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for EntryInfoType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for EntryInfoType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "Environment variables to set"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"Environment variables to set\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"additionalProperties\": {"]
#[doc = "    \"type\": \"string\""]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct EnvVars(pub ::std::collections::HashMap<::std::string::String, ::std::string::String>);
impl ::std::ops::Deref for EnvVars {
    type Target = ::std::collections::HashMap<::std::string::String, ::std::string::String>;
    fn deref(&self) -> &::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &self.0
    }
}
impl ::std::convert::From<EnvVars>
    for ::std::collections::HashMap<::std::string::String, ::std::string::String>
{
    fn from(value: EnvVars) -> Self {
        value.0
    }
}
impl ::std::convert::From<&EnvVars> for EnvVars {
    fn from(value: &EnvVars) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<::std::collections::HashMap<::std::string::String, ::std::string::String>>
    for EnvVars
{
    fn from(
        value: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    ) -> Self {
        Self(value)
    }
}
#[doc = "`Error`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"required\": ["]
#[doc = "    \"code\","]
#[doc = "    \"message\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"code\": {"]
#[doc = "      \"description\": \"Error code\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"message\": {"]
#[doc = "      \"description\": \"Error message\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Error {
    #[doc = "Error code"]
    pub code: i64,
    #[doc = "Error message"]
    pub message: ::std::string::String,
}
impl ::std::convert::From<&Error> for Error {
    fn from(value: &Error) -> Self {
        value.clone()
    }
}
#[doc = "Resource usage metrics"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"Resource usage metrics\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"properties\": {"]
#[doc = "    \"cpu_count\": {"]
#[doc = "      \"description\": \"Number of CPU cores\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"cpu_used_pct\": {"]
#[doc = "      \"description\": \"CPU usage percentage\","]
#[doc = "      \"type\": \"number\","]
#[doc = "      \"format\": \"float\""]
#[doc = "    },"]
#[doc = "    \"disk_total\": {"]
#[doc = "      \"description\": \"Total disk space in bytes\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"disk_used\": {"]
#[doc = "      \"description\": \"Used disk space in bytes\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"mem_total\": {"]
#[doc = "      \"description\": \"Total virtual memory in bytes\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"mem_used\": {"]
#[doc = "      \"description\": \"Used virtual memory in bytes\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"ts\": {"]
#[doc = "      \"description\": \"Unix timestamp in UTC for current sandbox time\","]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"format\": \"int64\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Metrics {
    #[doc = "Number of CPU cores"]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub cpu_count: ::std::option::Option<i64>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub cpu_used_pct: ::std::option::Option<f32>,
    #[doc = "Total disk space in bytes"]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub disk_total: ::std::option::Option<i64>,
    #[doc = "Used disk space in bytes"]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub disk_used: ::std::option::Option<i64>,
    #[doc = "Total virtual memory in bytes"]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub mem_total: ::std::option::Option<i64>,
    #[doc = "Used virtual memory in bytes"]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub mem_used: ::std::option::Option<i64>,
    #[doc = "Unix timestamp in UTC for current sandbox time"]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub ts: ::std::option::Option<i64>,
}
impl ::std::convert::From<&Metrics> for Metrics {
    fn from(value: &Metrics) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for Metrics {
    fn default() -> Self {
        Self {
            cpu_count: Default::default(),
            cpu_used_pct: Default::default(),
            disk_total: Default::default(),
            disk_used: Default::default(),
            mem_total: Default::default(),
            mem_used: Default::default(),
            ts: Default::default(),
        }
    }
}
